baseURL = "https://www.dinopedia-lepodcast.fr/"
languageCode = "fr"
title = "Dinopedia"
keywords = "dinosaures, podcast, animal, carnivore, herbivore, sciences, naturelle, apple, anchor, spotify"
theme = "massively"
defaultContentLanguage = "fr"

[params]
  # set below parameter to define a favicon
  favicon = "images/favicon.ico"
  description = "Le podcast français à propos de dinosaures, qui s'intéresse particulièrement au sens de leurs noms scientifiques"
  thumbnail = "images/introduction.jpg"

# Below parameters can be set to override default post settings
[params.posts]
  pageSize = "6"